Checkout flow
himanshumishra31/spree pull request #3
Opened 2018-02-23 09:04 UTC by himanshumishra31

2018-03-01 11:33 UTC, sawangupta92 requested changes

2018-03-01 11:33 UTC, sawangupta92 commented on app/controllers/spree/checkout_controller_decorator.rb
> +module Spree
we can also write it as Spree::CheckoutController.class_eval

this saves one extra indentation level

2018-03-05 11:07 UTC, harsh-ag requested changes

2018-03-05 11:07 UTC, harsh-ag commented on app/views/spree/checkout/edit.js.erb
> +  obj.init();
no need to create two methods over here

2018-03-05 11:07 UTC, harsh-ag commented on app/assets/javascripts/onepagecheckout.js
> +  this.enableCoffeeScript();
rename this method.

2018-03-13 07:26 UTC, merged